server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: changeme
    key-alias: localhost

app:
  auth-server: localhost
  eureka-server: localhost
  eureka-username: u
  eureka-password: p

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
    instance:
      leaseRenewalIntervalInSeconds: 5
      leaseExpirationDurationInSeconds: 5

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: https://dev-2nodnh1cai7yfl68.us.auth0.com/
          issuer-uri: http://${app.auth-server}:9999
  cloud:
    gateway:
      routes:
        - id: dashboard
          uri: lb://dashboard
          predicates:
            - Path=/dashboard/**
        - id: dashboard-swagger-ui
          uri: lb://dashboard
          predicates:
            - Path=/openapi/**
        - id: oauth2-server
          uri: lb://auth-server
          predicates:
            - Path=/oauth2/**
        - id: oauth2-login
          uri: lb://auth-server
          predicates:
            - Path=/login/**
        - id: oauth2-error
          uri: lb://auth-server
          predicates:
            - Path=/error/**
        - id: eureka-api
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring:
  config:
    activate:
      on-profile: docker

app:
  auth-server: auth-server
  eureka-server: eureka