server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: expense-db

logging:
  level:
    root: INFO
    com.akhil.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb